### ISSUE TITLE
Edu parser is incorrect and panics instead of handing the error

### ISSUE THREAD

**Issue by akissa** [likexian/whois-parser-go#24]
Hi

The `prepareEDU` does not do proper index checking thus leading to a panic.

panic: runtime error: index out of range [4] with length 4
```

goroutine 11 [running]:
github.com/likexian/whois-parser-go.prepareEDU(0xc00056f500, 0x643, 0xc00056f500, 0x643)
	/Users/andrew/Documents/devel/go/path/pkg/mod/github.com/likexian/whois-parser-go@v1.10.4/prepare.go:162 +0xd9f
github.com/likexian/whois-parser-go.Prepare(0xc00056f500, 0x643, 0xc00008e360, 0x3, 0xc00008e360, 0x3, 0xa)
	/Users/andrew/Documents/devel/go/path/pkg/mod/github.com/likexian/whois-parser-go@v1.10.4/prepare.go:40 +0x1ba
github.com/likexian/whois-parser-go.Parse(0xc00056e700, 0x644, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andrew/Documents/devel/go/path/pkg/mod/github.com/likexian/whois-parser-go@v1.10.4/parser.go:75 +0x195
```

The following domain will cause a panic.

```
Domain Name: RUTGERS.EDU

Registrant:
	Rutgers, The State University of New Jersey
	Office of Information Technology
	96 Davidson Road
	Piscataway, NJ 08854-8096
	USA

Administrative Contact:
	Domain Admin
	Office of Information Technology
	Telecommunications Division
	96 Davidson Road
	Piscataway, NJ 08854
	USA
	+1.8484457541
	netmanager@rutgers.edu

Technical Contact:
	Domain Admin
	Office of Information Technology
	Telecommunications Division
	96 Davidson Road
	Piscataway, NJ 08854
	USA
	+1.8484457541
	netmanager@rutgers.edu

Name Servers:
	NS8.A1.INCAPSECUREDNS.NET
	NS124.A2.INCAPSECUREDNS.NET
	NS87.A0.INCAPSECUREDNS.NET

Domain record activated:    25-Apr-1985
Domain record last updated: 25-Mar-2020
Domain expires:             31-Jul-2020
```

**Comment by likexian** [comment]
Hello @akissa 
This has been fixed, please try the latest version.

---
*If you think this repository is helpful, please share it with friends, thanks.*

**Comment by akissa** [comment]
Thanks
